# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
  resources:
  - repo: self
  variables :
    container_registery: ACR_ServiceEndpoint
    image_repo : test_arc_repo
    tag: 1
    aks_service_endpoint_name: AKS_serviceEndpoint
    acrurl : testacrregi01.azurecr.io
  stages:
  - stage: Build
    displayName: Build image
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          containerRegistry: '$(container_registery)'
          repository: '$(image_repo)'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          tags: |
                $(tag)
      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'AKS_serviceEndpoint'
          namespace: 'default'
          command: 'create'
          arguments: 'secret generic acrsecret --from-literal=username=admin --from-literal=password='Sadaf''
          secretType: 'generic'
      - task: KubernetesManifest@1
        inputs:
          action: 'deploy'
          connectionType: 'kubernetesServiceConnection'
          kubernetesServiceConnection: 'AKS_serviceEndpoint'
          namespace: 'default'
          manifests: '$(Build.SourcesDirectory)/azure-aks.yaml'
          containers: '$(acrurl)/$(image_Repo):$(tag)'
          imagePullSecrets: '$(acrsecret)'
